name: "Yarn install"
description: "Install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      name: Yarn Cache
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn Install
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 3
        retry_wait_seconds: 30
        max_attempts: 3
        command: yarn ci:install --prefer-offline
