name: Jest Tests
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/cancel_workflow
      - uses: ./.github/actions/yarn_install
      - run: yarn test --coverage
