name: Code Quality Checks

on: [workflow_dispatch, push]

jobs:
  ESLint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: ./.github/actions/yarn_install
      - name: Lint
        run: yarn eslint

  TypeScript:
    name: Types Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: ./.github/actions/yarn_install
      - name: Typescript check
        run: yarn ts-check
