name: Code Quality Checks

on: [workflow_dispatch, push]

jobs:
  ESLint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/cancel_workflow
      - uses: ./.github/actions/yarn_install
      - name: Lint
        run: yarn eslint

  TypeScript:
    name: Types Build Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/cancel_workflow
      - uses: ./.github/actions/yarn_install
      - name: Typescript check
        run: yarn ts-check

  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/cancel_workflow
      - name: swiftlint
        run: |
          function stripPWD() {
              if ! ${WORKING_DIRECTORY+false};
              then
                  cd - > /dev/null
              fi
              sed -E "s/$(pwd|sed 's/\//\\\//g')\///"
          }

          function convertToGitHubActionsLoggingCommands() {
              sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
          }
          set -o pipefail && yarn swiftlint | stripPWD | convertToGitHubActionsLoggingCommands

  JavaLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/cancel_workflow
      - uses: ./.github/actions/yarn_install
      - run: yarn javalint
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: android/build/reports/*.xml
        continue-on-error: false
