name: Release
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - next
      - alpha
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    if: github.event.repository.fork == false
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/yarn_install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
